module Yahoo
  class CalendarApi
    include HTTParty
    require 'securerandom'
    require 'time'
    require 'uri'
    # >>> base_uri "https://api.calendar.yahoo.com"
  
    def self.create_event(session, payload)
      oauth = Current.get_yahoo_oauth(session)
      puts '>>> oauth = ', oauth
      return auth_required if oauth.yahoo_oauth_in_progress?
      return auth_required unless oauth.yahoo_token_present?
  
      refresh_token(oauth) if oauth.yahoo_token_expired?
  
      response = send_event(oauth, payload)
      byebug
  
      return auth_required if response.code == 401
  
      if response.success?
        { ok: true }
      else
        { ok: false, error: :api_error, message: response.body }
      end
    end
  
    def self.send_event(oauth, payload)
      puts '>>> going to send now with', payload
      byebug
      
      calendar_url = "https://caldav.calendar.yahoo.com/dav/unikoski/Calendar/"
      uid = SecureRandom.uuid
      event_filename = "#{uid}.ics"

      uri = URI.join(calendar_url, event_filename)
      puts '>>> uri = ', uri

      put(
        uri,
        headers: {
          "Authorization" => "Bearer #{oauth.yahoo_access_token}",
          "Content-Type" => "text/calendar"
        },
        body: build_ics_event(payload, uid)
      )
    end
  
    def self.refresh_token(oauth)
      response = HTTParty.post(
        "https://api.login.yahoo.com/oauth2/get_token",
        basic_auth: {
          username: YahooOauthController.get_client_id,
          password: YahooOauthController.get_client_secret
        },
        body: {
          grant_type: "refresh_token",
          refresh_token: oauth.yahoo_refresh_token
        }
      )
  
      return false unless response.success?
  
      oauth.finish_oauth!(
        response["access_token"],
        response["refresh_token"] || oauth.yahoo_refresh_token,
        response["expires_in"]
      )
    end
  
    def self.auth_required
      { ok: false, error: :auth_required }
    end

    def self.build_ics_event(payload, uid)
      puts '>>> how close does payload mathch this???', payload
      uid = SecureRandom.uuid
      now = Time.now.utc.strftime("%Y%m%dT%H%M%SZ")

      <<~ICS
      BEGIN:VCALENDAR
      VERSION:2.0
      PRODID:-//MyApp//Yahoo CalDAV//EN
      BEGIN:VEVENT
      UID:#{uid}
      DTSTAMP:#{now}
      DTSTART:20260210T080000Z
      DTEND:20260210T083000Z
      SUMMARY:Trial by thingi
      DESCRIPTION:Auto-generated by Share Alerts
      END:VEVENT
      END:VCALENDAR
      ICS
    end

  end
end
