class DashboardController < ApplicationController
  def index
    # Your logic here if needed
    
    # Render the index view
    render 'index'
  end
  
  def create_calendar_event
    puts '>>> entered create_calendar_event'
    byebug
    result = Yahoo::Calendar.new.create_yahoo_calendar_event(
      session,
      "Dividend Review",
      Time.zone.parse("2026-02-10 10:00"),
      Time.zone.parse("2026-02-10 10:30"),
      notes: "Auto-generated by Share Alerts"
    )

    if result[:success]
      redirect_to root_path, notice: "Calendar event created"
    elsif result[:action] == :oauth_required
      session[:post_oauth_action] = result[:resume_payload]
      redirect_to result[:redirect_to]
    else
      redirect_to root_path # >>> , alert: result[:message]
    end
  end

  def load_email_body
    mm = Yahoo::Email.new(Yahoo::Email.email_actions[:get_message_body], params[:id])
    render plain: mm.get_mail_body, status: :ok
  end
end
